version: '3.8'
services:
  db-dsy:
    build:
      context: .\Database\
    image: dsy-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
  service1-dsy:
    build:
      context: .\Service\
    image: dsy-service1
    restart: always
    ports:
      - "3033:3033"
    depends_on:
      - db-dsy   
  frontend:
    build:
      context: /Frontend
    image: dsy-frontend
    ports:
      - "8080:80"
    restart: on-failure
  loadbalancer:
    build:
      context: /Loadbalancer
    image: dsy-loadbalancer
    ports:
      - "3020:3020"
    restart: always