version: '3.9'
services:

  db-dsy:
    build:
      context: .\Database\
    image: dsy-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
      
  service1-dsy:
    build:
      context: .\Service\
    image: dsy-service1
    restart: always
    ports:
      - "3033:3033"
    depends_on:
      - db-dsy
    environment:
      PORT: 3033
      DBHOST: db-dsy
      DBPORT: 5432
      
  service2-dsy:
    build:
      context: .\Service\
    image: dsy-service1
    restart: always
    ports:
      - "3034:3034"
    depends_on:
      - db-dsy
    environment:
      PORT: 3034
      DBHOST: db-dsy
      DBPORT: 5432
      
  frontend:
    build:
      context: /Frontend
    image: dsy-frontend
    ports:
      - "8080:80"
    restart: on-failure
    
  loadbalancer:
    build:
      context: /Loadbalancer
    image: iuridiniz/haproxy:2.7.3
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    volumes:
    - ./loadbalancer/haproxy.cfg:/etc/haproxy/haproxy.cfg
    - ./loadbalancer/PEM/certificate.crt:/etc/haproxy/PEM/certificate.crt
    restart: always
    depends_on: 
      - service1-dsy
      - service2-dsy